/**
 * CCO (GPT-5 with GPT-4o fallback) — Zod schema for Arabic QC output.
 *
 * Mirrors the JSON contract in prompts/OGzStudios_CCO_Prompt_v1.md.
 * The CCO returns a JSON ARRAY (one entry per evaluated post). Per the prompt:
 *   "Never skip a post — if you cannot evaluate one, return it with
 *    score: 0 and issues: ['evaluation_failed']."
 */
import { z } from 'zod'

export const NegPatFlag = z.enum(['NONE', 'SOFT_WARN', 'STRONG_WARN', 'HARD_BLOCK'])
export type NegPatFlag = z.infer<typeof NegPatFlag>

/** Issue tags — the prompt enumerates the controlled vocabulary. */
export const CcoIssue = z.enum([
  'translation_smell',
  'dialect_mismatch',
  'tone_drift',
  'anti_attribute_violation',
  'cultural_insensitivity',
  'hashtag_issue',
  'grammar_error',
  'religious_reference_uncleared',
  'competitor_reference',
  'price_claim_prohibited',
  'evaluation_failed',
  // v2 method-adherence issues (one per scored component) — emitted when a
  // caption contradicts the brand's composed method_profile. Surfaced in the
  // QA UI so admins see exactly which brand-method dimension the post broke.
  'voice_register_mismatch',
  'opening_pattern_mismatch',
  'visual_brief_mismatch',
  'cadence_role_mismatch',
  'closing_pattern_mismatch',
  // Emitted when no method_profile reached the CCO — method scoring defaulted
  // to neutral (50). A visible signal that the post was NOT graded on brand method.
  'no_method_profile',
])
export type CcoIssue = z.infer<typeof CcoIssue>

export const CcoPostEvaluation = z.object({
  post_id: z.string(),
  score: z.number().int().min(0).max(100),
  dialect_flag: z.boolean(),
  negpat_flag: NegPatFlag,
  cultural_flag: z.boolean(),
  brave_route_flag: z.boolean(),
  // Allow free-form strings for forward-compat, but prefer the controlled vocab above.
  issues: z.array(z.union([CcoIssue, z.string()])),
  // v2 method-adherence sub-score (0–100): the 30% method component of `score`.
  // Optional so v1-style responses still validate; null/absent = not graded.
  method_adherence_score: z.number().int().min(0).max(100).nullable().optional(),
})
export type CcoPostEvaluation = z.infer<typeof CcoPostEvaluation>

/** CCO returns a top-level JSON array. */
export const CcoResponse = z.array(CcoPostEvaluation)
export type CcoResponse = z.infer<typeof CcoResponse>

// ── Input ──────────────────────────────────────────────────────────
export interface CcoCaptionInput {
  post_id: string
  caption_ar: string
  content_type?: string
  hashtags?: string[]
  posting_time?: string
  // CCO scoring hints generated by DeepSeek — guide keyword-based scoring adjustments.
  // Always arrays (never null) — empty array means no hints for this post.
  positive_keywords?: string[]
  negative_keywords?: string[]
  // The English visual brief DeepSeek produced for this post. The CCO v2
  // prompt's Method Component 3 (visual_idiom) scores the brief against the
  // brand's visual idiom — without it that component can't be graded.
  visual_brief_en?: string
  // The post's strategic objective — Method Component 4 (cadence_role) scores
  // whether this content_type/objective fits the brand's cadence rule.
  objective?: string
}

/**
 * The brand's composed method profile (BrandDNA v2, brand_method_profiles).
 * These five components are the ground truth the CCO v2 prompt grades method
 * adherence against (voice/opening/visual/cadence/closing, each 0–25). They
 * already exist inside the compiled caption context — passing them STRUCTURED
 * (rather than buried in a truncated prose excerpt) is what makes the 30%
 * method-adherence weight in the score formula actually function.
 */
export interface CcoMethodProfile {
  voice_register?: string
  diagnostic_pattern?: string
  visual_idiom?: string
  cadence_rule?: string
  closing_pattern?: string
}

export interface CcoInput {
  brand_id: string
  caption_context_excerpt: string // brand voice + dialect + anti-attributes (no prompts)
  posts: CcoCaptionInput[]
  // Structured method profile from the caption context. Optional for backward
  // compatibility — when absent, the CCO prompt sets method_adherence_score to
  // 50 (neutral) and emits issues: ['no_method_profile'], which the QA UI now
  // surfaces so the gap is visible rather than silent.
  method_profile?: CcoMethodProfile
}
