// Hand-maintained domain types — kept concise for UI consumption.
// For a fully-typed Supabase client, later run `supabase gen types typescript`
// and swap `Database` below with the generated one.

export type Sector = 'F&B' | 'Retail' | 'Beauty_Wellness' | 'Healthcare' | 'Finance' | 'Government' | 'Other'
export type Dialect = 'Najdi' | 'Hejazi' | 'Gulf' | 'MSA_formal' | 'MSA_accessible' | 'Mixed'
export type PricePosition = 'budget' | 'mid_market' | 'premium' | 'luxury'
export type ReligiousSensitivity = 'Low' | 'Medium' | 'High'
export type Tier = 'free' | 'paid_starter' | 'paid_pro'
export type PipelineTier = 'Starter' | 'Pro'
export type ConfidenceMode = 'Standard' | 'Cautious' | 'Minimal' | 'Blocked'
export type FieldConfidence =
  | 'explicitly_confirmed'
  | 'inferred_high'
  | 'inferred_medium'
  | 'inferred_low'
  | 'rejected'
  | 'deprecated'
export type Channel = 'Instagram' | 'Snapchat' | 'TikTok' | 'Twitter'
// 'generated' = produced by n8n but not yet released to the client; admin flips
// it to 'pending' (client-visible) via the QA / content-release surfaces.
// 'pending_review' = on-demand media generated by N8N-A02 but held for admin
// moderation (Generate-Then-Review). Flipped to 'approved' on release, or
// 'rejected' on reject — both via the QA actions. calendar_posts.status is a
// free-text column in Postgres, so this union just documents the known values.
export type PostStatus = 'draft' | 'generated' | 'pending' | 'pending_review' | 'approved' | 'rejected'
export type PublishStatus = 'unscheduled' | 'scheduled' | 'published' | 'failed' | 'manual_required'
export type QaStatus = 'pending' | 'approved' | 'rejected' | 'edited'
export type NegpatSeverity = 'SOFT_WARN' | 'STRONG_WARN' | 'HARD_BLOCK'

// v2 axis enums (mirror Postgres enum types from migration 0020)
export type ArchetypeV2 =
  | 'Innocent' | 'Sage' | 'Explorer' | 'Outlaw'
  | 'Magician' | 'Hero' | 'Lover' | 'Jester'
  | 'Everyman' | 'Caregiver' | 'Ruler' | 'Creator'
export type LifecycleStage = 'pre_launch' | 'launch' | 'growth' | 'maturity' | 'recovery'
export type IntentState = 'launch' | 'grow' | 'defend' | 'harvest' | 'recover'
// Layer 2 enums (migration 0043)
export type ComfortOnCamera = 'willing' | 'hesitant' | 'not_interested'
export type WayOfSpeaking = 'formal' | 'casual' | 'storytelling' | 'direct'
// Layer 4 enums (migration 0043)
export type PermissionLevel = 'category_leader' | 'challenger' | 'institutional' | 'purpose' | 'launch' | 'sme_local'
export type GoalPhase = 'awareness' | 'conversion' | 'retention' | 'launch'
// Layer 3 — Visual register (migration 0086)
export type StyleRegister = 'traditional' | 'modern' | 'youth' | 'mixed'
// Layer 3 — LoRA training status (migration 0077)
export type LoraTrainingStatus = 'not_started' | 'collecting_photos' | 'training' | 'ready' | 'failed'
// Layer 6 — Content pattern type (migration 0078)
export type ContentPatternType = 'winner' | 'loser'
// Layer 5 — Asset types (migration 0077)
export type AssetType = 'logo' | 'product' | 'location' | 'team' | 'hero' | 'brand_material' | 'approved_post' | 'rejected_post' | 'brand_asset'

export interface BrandProfile {
  brand_id: string
  brand_name_ar: string
  brand_name_en: string | null
  sector: Sector
  city_primary: string | null
  arabic_dialect: Dialect | null
  price_position: PricePosition | null
  brand_differentiator: string | null
  religious_sensitivity: ReligiousSensitivity | null
  bilingual_ratio: 'arabic_only' | 'arabic_primary' | 'balanced' | 'english_primary' | null
  formality_level: 'casual' | 'semi_formal' | 'formal' | null
  humor_tolerance: 'none' | 'light' | 'moderate' | null
  ramadan_relevance: 'Critical' | 'High' | 'Medium' | 'Low' | 'Not_relevant' | null
  primary_kpi_type: 'engagement' | 'conversion' | 'awareness' | 'trust' | null
  tone_anti_attribute_ids: string[]
  primary_channel: Channel | null
  tier: Tier
  pipeline_tier: PipelineTier
  batch_shard: number
  client_slug: string
  logo_url: string | null
  primary_color_hex: string | null
  completeness_score: number
  total_calendars_generated: number
  // v2 — three-axis creative direction (added by migration 0020)
  archetype_primary: ArchetypeV2 | null
  archetype_secondary: ArchetypeV2 | null
  lifecycle_stage: LifecycleStage | null
  intent_state: IntentState | null
  // Layer 1 additions (migration 0060)
  sub_sector?: string | null
  region_primary?: string | null
  founded_year?: number | null
  tone_register?: string | null
  // Layer 2 — Owner Profile (migration 0043 + 0059 + 0060)
  founding_story?: string | null
  comfort_on_camera?: ComfortOnCamera | null
  physical_appearance_notes?: string | null
  way_of_speaking?: WayOfSpeaking | null
  content_preferences?: unknown[] | null
  owner_values?: string | null
  communication_style?: string | null
  brand_goals?: string | null
  // Layer 3 — Visual/Content Identity (migration 0060 + 0077)
  posting_rhythm?: string | null
  caption_style?: string | null
  lora_model_id?: string | null
  lora_trained_at?: string | null
  lora_training_status?: LoraTrainingStatus | null
  lora_approved_content_types?: string[] | null
  lora_training_photo_count?: number | null
  // Layer 6 — Calibration period (migration 0078)
  is_calibration_period?: boolean | null
  calibration_started_at?: string | null
  calibration_ends_at?: string | null
  calibration_ended_reason?: string | null
  // Layer 4 — Strategic Intelligence (migration 0043)
  permission_level?: PermissionLevel | null
  cultural_tension_owned?: string | null
  creative_formulas_approved?: string[]
  brave_safe_default?: boolean | null
  strategy_version?: number | null
  content_mix_ratios?: Record<string, number> | null
  platform_weights?: Record<string, number> | null
  goal_phase?: GoalPhase | null
  occasion_approach?: Record<string, string> | null
  business_events?: Array<{ type: string; title: string; date?: string; description?: string }> | null
  // Audit columns added later in the schema lifetime. Optional because the
  // generated database.types.ts is only refreshed via `pnpm db:types`; if it
  // hasn't been re-run since the most recent migration, the column will be
  // missing from the inferred row type.
  sector_baseline_id?: string | null
  vector_namespace?: string | null     // mig 0030
  instagram_handle?: string | null
  website_url?: string | null
  place_id?: string | null
  onboarding_status?: string | null
  created_at: string
  updated_at: string
  postiz_workspace_id?: string | null
}

export interface BrandSnapshot {
  snapshot_id: string
  brand_id: string
  is_partial: boolean
  snapshot_data: {
    tones?: string[]
    visual_style?: string
    audience?: string
    completeness?: number
    dialect_confirmed?: boolean
  }
  created_at: string
}

// Calendar lifecycle (migration 0076). 'delivered' is the terminal
// "released to client / ready" state; 'pending_review' = awaiting OGZ release.
export type CalendarStatus =
  | 'draft'
  | 'generating'
  | 'pending_review'
  | 'delivered'
  | 'rejected'

export interface Calendar {
  calendar_id: string
  brand_id: string
  month: string
  status: CalendarStatus
  intent_override: 'launch' | 'grow' | 'defend' | 'harvest' | 'recover' | null
  created_at: string
  delivered_at: string | null
  reviewed_at: string | null
  /** Admin auth user id (uuid as text) that released/rejected. No PII. */
  reviewed_by: string | null
  /** Client-facing reason shown when status = 'rejected'. */
  rejection_reason: string | null
  /** Timestamp when n8n brand_complete fires. NULL for pre-migration rows. */
  generated_at: string | null
  /** n8n $execution.id for the A01 run that produced this calendar. */
  n8n_execution_id: string | null
  /** How the run was initiated: 'cron_monthly' | 'cron_weekly' | 'webhook_manual' | 'manual' */
  workflow_trigger: string | null
  regeneration_count: number
  review_required: boolean
}

export interface CaptionVariant {
  caption_ar: string
  hashtags: string[]
  tone: string
}

export interface CalendarPost {
  post_id: string
  calendar_id: string | null
  brand_id: string
  position: number
  caption_ar: string | null
  hashtags: string[]
  content_type: string | null
  /** Produced output medium (migration 0075). 'image' for every legacy/image post; 'video' for Fal video posts. */
  media_type: 'image' | 'video'
  /** Clip length in seconds for video posts (migration 0075). NULL for images. */
  video_duration_s: number | null
  posting_time: string | null
  storage_url: string | null
  /** Pre-overlay (no Arabic typography) variant. NULL for legacy posts predating migration 0036, and always NULL for video. */
  clean_storage_url: string | null
  format_tier: 'image' | 'video'
  confidence_score: number | null
  watermark: boolean
  status: PostStatus
  approved_at: string | null
  postiz_post_id: string | null
  publish_status: PublishStatus
  published_at: string | null
  revision_count: number
  created_at: string
  on_demand_request_id: string | null
  caption_variants: CaptionVariant[] | null
  selected_variant_index: number | null
  /** For video posts: 'processing' while fal.ai job is in-flight, 'completed' on success, 'failed' on FAILED webhook. NULL for image posts. */
  video_status: 'processing' | 'completed' | 'failed' | null
  /** Number of times generation has been attempted (0 = not yet). */
  generation_attempt: number
  /** Last error from a failed generation. Cleared on successful regeneration. */
  last_error: string | null
  /** English visual brief assembled by the prompt-composer (migration 0100). Fed to fal.ai. */
  image_prompt_en: string | null
  /** GPT-4o vision score (0-100) for the generated image (migration 0117). NULL until visual QC runs. */
  visual_score: number | null
  /** Visual issues flagged by the visual QC pass — array of {code, label, severity, detail?} (migration 0117). */
  visual_issues: Array<{ code: string; label: string; severity: 'high' | 'med' | 'low'; detail?: string }> | null
}

export interface QaQueueItem {
  queue_id: string
  brand_id: string
  post_id: string | null
  caption_ar: string | null
  cco_score: number | null
  flags: Record<string, unknown>
  trigger_reason: string | null
  status: QaStatus
  created_at: string
  /**
   * Optional enrichment for on-demand QA rows (Generate-Then-Review). Populated
   * by {@link getQaQueuePaged} for `on_demand` items so the admin can preview the
   * already-generated media before deciding. Absent for calendar rows and any
   * row whose linked post/request could not be resolved.
   */
  media?: QaQueueMedia | null
  request?: QaQueueRequest | null
  /**
   * Key brand profile fields enriched onto every on-demand QA row so the admin
   * card can display brand name, sector, pipeline tier, and channel without a
   * separate fetch. Populated by {@link getQaQueuePaged} alongside `media`.
   */
  brand?: QaQueueBrand | null
  /**
   * Admin-only draft regenerations (newest first) for this on-demand post,
   * from the {@link AdminRegeneration} table. Populated only for `on_demand`
   * rows; never exposed to clients (table is service-role-only). Empty array
   * when the post has no admin drafts.
   */
  admin_regenerations?: AdminRegenerationSummary[] | null
  /**
   * Selected creative chain for this on-demand post (from `chains` via
   * calendar_posts.chain_id). NULL when standard model routing was used.
   * Populated only for `on_demand` rows.
   */
  chain?: QaQueueChain | null
}

/** Generated media snapshot for an on-demand QA row (from calendar_posts). */
export interface QaQueueMedia {
  post_id: string
  media_type: 'image' | 'video'
  storage_url: string | null
  clean_storage_url: string | null
  hashtags: string[]
  caption_ar: string | null
  confidence_score: number | null
  watermark: boolean
  chain_id: string | null
  /** Model actually resolved/called at generation (calendar_posts.generation_model). NULL = not recorded. */
  generation_model: string | null
  /** Final English prompt actually sent to fal.ai (calendar_posts.image_prompt_en). NULL = not recorded. */
  image_prompt_en: string | null
  /** Route taken (clean/watermark/hold) recorded on the post (calendar_posts.route_decision). */
  route_decision: string | null
}

/** Originating brief metadata for an on-demand QA row (from on_demand_requests). */
export interface QaQueueRequest {
  request_id: string
  hero_concept: string | null
  style_descriptor: string | null
  content_type: string | null
  platform: string | null
  media_type: 'image' | 'video'
  current_step: string | null
  /** Requested image model preference for the brief (on_demand_requests.image_model_pref). */
  image_model_pref: string | null
  /** User-supplied negative prompt for the brief (on_demand_requests.negative_prompt). */
  negative_prompt: string | null
  /** Cultural guidance note the client attached to the brief (on_demand_requests.cultural_guidance). */
  cultural_guidance: string | null
  /** CEO confidence mode set at routing (on_demand_requests.confidence_mode). */
  confidence_mode: string | null
  /** Brand colour palette requested for the brief (on_demand_requests.color_palette). */
  color_palette: string[] | null
  /** Occasion name attached to the brief, if any (on_demand_requests.occasion_name). */
  occasion_name: string | null
}

/**
 * Selected creative chain for an on-demand QA row, resolved from `chains` via
 * calendar_posts.chain_id. NULL when the post used standard model routing
 * (on-demand generation does not use the chain system — Doc §9.5 applies to the
 * calendar slot planner).
 */
export interface QaQueueChain {
  chain_id: string
  name_en: string | null
  name_ar: string | null
  family: string | null
  /** The model the chain calls (chains.fal_model_primary). */
  fal_model_primary: string | null
  /** The chain's prompt template / recipe (chains.prompt_template). */
  prompt_template: string | null
  /** The chain's negative prompt (chains.negative_prompt). */
  negative_prompt: string | null
}

/** Key brand profile fields enriched onto on-demand QA rows (from brand_profiles). */
export interface QaQueueBrand {
  brand_name_ar: string
  brand_name_en: string | null
  sector: Sector
  tier: Tier
  pipeline_tier: PipelineTier
  primary_channel: Channel | null
  arabic_dialect: Dialect | null
  client_slug: string
  logo_url: string | null
}

/**
 * Lifecycle of an admin draft regeneration (migration 0099).
 *   draft      — produced by N8N-B03 (target=admin), awaiting admin decision.
 *   approved   — promoted into calendar_posts (now the live/published asset).
 *   rejected   — discarded by admin; remains in history, never published.
 *   superseded — another version for the same post was approved instead.
 */
export type AdminRegenStatus = 'draft' | 'approved' | 'rejected' | 'superseded'

/** Prompt override captured for an admin regeneration (English only — Hard Rule #3). */
export interface AdminRegenPromptOverride {
  style_descriptor?: string
  hero_concept?: string
  negative_prompt?: string
  cultural_guidance?: string
}

/**
 * A single admin draft regeneration version (migration 0099, admin_regenerations).
 * Lives in a separate "draft lane" so admin regenerations never touch the live
 * calendar_posts row until an admin approves one. Service-role access only.
 */
export interface AdminRegeneration {
  regen_id: string
  post_id: string
  request_id: string | null
  brand_id: string
  version: number
  media_type: 'image' | 'video'
  storage_url: string
  clean_storage_url: string | null
  caption_ar: string | null
  hashtags: string[]
  confidence_score: number | null
  watermark: boolean
  prompt_override: AdminRegenPromptOverride | null
  image_model: string | null
  status: AdminRegenStatus
  created_by: string | null
  created_at: string
  reviewed_at: string | null
  reviewed_by: string | null
  /** GPT-4o visual QC score (0-100). NULL until visual-qc runs post-generation. */
  visual_score: number | null
  /** Visual issues from visual-qc. NULL until scored. */
  visual_issues: Array<{ code: string; label: string; severity: 'high' | 'med' | 'low'; detail?: string }> | null
}

/** Draft-version summary rendered on the admin QA card (subset of {@link AdminRegeneration}). */
export interface AdminRegenerationSummary {
  regen_id: string
  post_id: string
  version: number
  media_type: 'image' | 'video'
  storage_url: string
  clean_storage_url: string | null
  caption_ar: string | null
  hashtags: string[]
  confidence_score: number | null
  watermark: boolean
  prompt_override: AdminRegenPromptOverride | null
  image_model: string | null
  status: AdminRegenStatus
  created_by: string | null
  created_at: string
  /** GPT-4o vision score (0-100) from visual-qc run after regeneration. NULL = not yet scored. 0 = hard block. */
  visual_score: number | null
  /** Structured visual issues from visual-qc: [{code, label, severity, detail?}]. NULL until scored. */
  visual_issues: Array<{ code: string; label: string; severity: 'high' | 'med' | 'low'; detail?: string }> | null
}

export interface RoutingDecision {
  decision_id: string
  brand_id: string | null
  flow_id: string
  request_type: string | null
  pipeline_assigned: string | null
  agents_dispatched: string[]
  constraints_applied: Record<string, unknown>
  confidence_mode: ConfidenceMode | null
  outcome: string | null
  timestamp: string
}

export interface AnomalyRecord {
  anomaly_id: string
  brand_id: string | null
  anomaly_type: string
  severity: string
  source_flow: string | null
  message: string | null
  details: Record<string, unknown>
  resolved: boolean
  created_at: string
}

export interface UsageLog {
  log_id: string
  brand_id: string | null
  flow_id: string | null
  node_name: string | null
  cost_usd: number
  duration_ms: number | null
  status: string | null
  created_at: string
  /** fal.ai async queue request ID. Added in migration 0075. */
  fal_request_id: string | null
  /** FK to calendar_posts(post_id). Added in migration 0075. */
  post_id: string | null
  provider?: string | null
  // New from migration 0074:
  client_slug?: string | null
  flow_run_id?: string | null
  request_type?: string | null
  model?: string | null
  agent?: string | null
  tokens_in?: number | null
  tokens_out?: number | null
  tokens_cached?: number | null
  images_generated?: number | null
  cost_usd_input?: number | null
  cost_usd_output?: number | null
  cost_usd_cached?: number | null
  monthly_ceiling_usd?: number | null
  error_code?: string | null
}

export interface BrandCostConfig {
  brand_id: string
  monthly_ceiling_usd: number
  tier: string
  alert_at_pct: number
  halt_at_pct: number
  updated_at: string
}

export interface SystemCostConfig {
  monthly_ceiling_usd: number
  alert_at_pct: number
  halt_at_pct: number
}

export interface CostMonthOption {
  month_iso: string
  calls: number
  total_spend: number
}

export interface MonthlyCostBrand {
  brand_id: string
  brand_name_ar: string
  brand_name_en: string | null
  client_slug: string
  sector: string | null
  total_spend: number
  ai_spend: number
  image_spend: number
  video_spend: number
  calls: number
  monthly_ceiling_usd: number
  cost_blocked: boolean
  last_alert_type: string | null
  spend_pct: number
  cost_status: 'normal' | 'approaching' | 'critical' | 'breached'
}

export interface MonthlyCostSummary {
  month: string
  total_spend: number
  total_calls: number
  by_request_type: Record<string, number>
  by_agent: Record<string, number>
  by_flow: Record<string, number>
  brands: MonthlyCostBrand[]
}

export interface BrandMonthlySummary {
  brand_id: string
  brand_name_ar: string
  brand_name_en: string | null
  client_slug: string
  sector: string
  tier: string
  monthly_ceiling_usd: number
  current_month_spend_usd: number
  spend_pct: number
  cost_status: 'normal' | 'approaching' | 'critical' | 'breached'
  call_count: number
  last_call_at: string | null
}

export interface EvidenceBundle {
  bundle_id: string
  brand_id: string
  field_name: string
  field_confidence: FieldConfidence
  agreement_ratio: number
  recency_score: number
  conflict_score: number
  last_evaluated: string
}

export interface SectorBaseline {
  baseline_id: string
  sector: Sector
  dialect: Dialect
  sample_size: number
  recommended_content_mix: Record<string, number>
  top_performing_tones: Array<{ tone_id: string; approval_rate: number; sample: number }>
  worst_performing_tones: Array<{ tone_id: string; approval_rate: number; sample: number }>
  occasion_insights: Record<string, unknown>
  confidence_benchmarks: Record<string, unknown>
  last_updated: string
}

export interface BusinessEvent {
  event_id: string
  brand_id: string
  event_type: string
  title: string
  description: string | null
  event_date: string | null
  end_date: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface StrategyUpdateLog {
  log_id: string
  brand_id: string
  strategy_version: number
  changed_fields: string[]
  change_summary: string | null
  trigger_type: string | null
  triggered_by: string | null
  client_notified: boolean
  created_at: string
}

export interface CulturalTensionRegistry {
  registry_id: string
  brand_id: string
  tension_text: string
  sector: string
  city_primary: string | null
  claimed_at: string
  released_at: string | null
  is_active: boolean
}

export interface Occasion {
  occasion_id: string
  occasion_key: string
  occasion_name_ar: string
  occasion_name_en: string | null
  year: number
  gregorian_date: string
  lead_weeks: number
  priority: 'Critical' | 'High' | 'Medium' | 'Low' | 'Not_relevant'
  recommended_mix: Record<string, number>
  sector_applicability: Record<string, boolean>
}

// ── Brand Scorecard (scoring schema — migration 0061) ─────────────────────────

export type ScoreTier = 'low' | 'mid' | 'high'
export type ScoreStatus = 'complete' | 'preliminary' | 'stale' | 'error'
export type ScoreScanTier = 'free' | 'paid' | 'subscription'
export type ScoreDimension =
  | 'visual_quality'
  | 'cultural_fit'
  | 'posting_consistency'
  | 'brand_coherence'
  | 'engagement_health'

export interface ScoreCard {
  id: string
  handle: string
  brand_name_en: string | null
  brand_name_ar: string | null
  sector: string
  location_city: string | null
  location_neighborhood: string | null
  location_lat: number | null
  location_lng: number | null
  followers_count: number | null
  posts_analyzed: number
  overall_score: number
  score_status: ScoreStatus
  tier: ScoreTier
  scanned_at: string
  expires_at: string
  brand_dna_id: string | null
  share_slug: string
  share_views: number
  share_count: number
  scan_tier: ScoreScanTier
  error_message: string | null
  created_at: string
}

export interface ScoreDimensionRow {
  id: string
  score_card_id: string
  dimension: ScoreDimension
  score: number
  weight: number
  benchmark: number | null
  submetrics: Record<string, unknown>
  created_at: string
}

export interface ScoreFinding {
  id: string
  score_card_id: string
  dimension: ScoreDimension
  finding_en: string
  finding_ar: string
  evidence_count: number | null
  evidence_total: number | null
  benchmark_count: number | null
  severity: 'high' | 'mid' | 'low'
  created_at: string
}

export interface ScoreAction {
  id: string
  score_card_id: string
  dimension: ScoreDimension
  workflow_id: string
  action_label_en: string
  action_label_ar: string
  estimated_lift: number
  timeframe_weeks: number
  icon_emoji: string | null
  created_at: string
}

export interface CompetitorScore {
  id: string
  score_card_id: string
  competitor_handle: string
  competitor_name: string
  competitor_score: number
  distance_meters: number | null
  location_label_en: string | null
  location_label_ar: string | null
  rank: number
  is_focal_brand: boolean
  tier: ScoreTier
  created_at: string
}

export interface SectorBenchmarkRow {
  id: string
  sector: string
  dimension: string
  submetric: string
  p25: number | null
  p50: number | null
  p75: number | null
  p90: number | null
  sample_size: number
  computed_at: string
}

// Full scorecard with all related data — used by the public page + admin inspector
export interface FullScoreCard {
  card: ScoreCard
  dimensions: ScoreDimensionRow[]
  findings: ScoreFinding[]
  actions: ScoreAction[]
  competitors: CompetitorScore[]
}

// ── Layer 3 — Asset Library (migration 0077) ──────────────────────────────────
export interface AssetLibraryItem {
  asset_id: string
  brand_id: string
  storage_url: string
  file_name: string
  mime_type: string
  file_size_bytes: number | null
  asset_type: AssetType
  is_approved: boolean | null
  approved_at: string | null
  rejected_at: string | null
  rejection_reason: string | null
  dominant_colors: string[] | null
  visual_style_tags: string[] | null
  detected_objects: string[] | null
  used_in_posts: string[] | null
  lora_training_candidate: boolean
  source: 'client_upload' | 'extraction' | 'generated'
  uploaded_at: string
  notes: string | null
  created_at: string
  updated_at: string
}

// ── Layer 6 — Content Pattern Winners/Losers (migration 0078) ─────────────────
export interface BrandContentPattern {
  pattern_id: string
  brand_id: string
  pattern_type: ContentPatternType
  content_type: string
  chain_family: string | null
  formula_used: string | null
  register_used: string | null
  occasion: string | null
  trigger_signal: string
  avg_engagement_rate: number | null
  sample_count: number
  confidence: number
  content_mix_shift: Record<string, number> | null
  is_active: boolean
  invalidated_at: string | null
  invalidation_reason: string | null
  first_observed_at: string
  last_updated_at: string
  created_at: string
}

// ── Layer 5 — Competitor Snapshots (migration 0076 + 0082) ───────────────────
export interface CompetitorSnapshot {
  snapshot_id: string
  competitor_id: string
  brand_id: string
  snapshot_type: 'light' | 'deep'
  extracted_at: string
  posting_frequency_per_week: number | null
  best_posting_days: string[] | null
  best_posting_hours: number[] | null
  platforms_active: string[] | null
  follower_counts: Record<string, number> | null
  content_category_distribution: Record<string, number> | null
  estimated_engagement_rate: number | null
  top_performing_content_types: string[] | null
  top_performing_tones: string[] | null
  caption_style_observed: string | null
  visual_style_observed: string | null
  cultural_tensions_used: string[] | null
  gaps_identified: string[] | null
  threats_identified: string[] | null
  // Added migration 0089
  occasion_approach: Record<string, 'full' | 'reduced' | 'minimal' | 'none'> | null
  engagement_by_content_type: Record<string, number> | null
  raw_payload: Record<string, unknown> | null
  normalised: Record<string, unknown> | null
  created_at: string
}

export interface CompetitorAccount {
  competitor_id: string
  brand_id: string
  handle_instagram: string | null
  handle_tiktok: string | null
  handle_snapchat: string | null
  handle_youtube: string | null
  handle_x: string | null
  display_name: string | null
  sector: string | null
  tier: 'light' | 'deep'
  is_active: boolean
  added_at: string
  last_extracted_at: string | null
  notes: string | null
}

export interface CompetitorAlert {
  alert_id: string
  brand_id: string
  competitor_id: string | null
  alert_type: 'gap_opportunity' | 'major_campaign' | 'platform_join' | 'engagement_spike' | 'occasion_move' | 'weekly_summary'
  severity: 'info' | 'warning' | 'urgent'
  title: string
  body: string
  suggested_content_direction: string | null
  is_read: boolean
  is_actioned: boolean
  actioned_at: string | null
  client_decision: 'accepted' | 'ignored' | 'adjusted' | null
  created_at: string
}
