/**
 * Admin server actions — QA queue approve/reject.
 *
 * Requires admin auth (validated server-side, not just by proxy).
 * On resolve:
 *   - Sets status + resolved_at + reviewed_at (migration 0019 column)
 *   - Fires email notification via @repo/email notify() — fire-and-forget
 *   - If post_id present and approved, fires N8N-QA-Approved webhook
 *   - Writes a usage_logs row for audit per HARD RULE #2 spirit
 */
'use server'

import { revalidatePath } from 'next/cache'
import { adminClient } from '@repo/db/client'
import { adminQ, getPendingCalendarQaIdsForBrand } from '@repo/db'
import { requireAdmin } from '@repo/auth/admin'
import { notify } from '@repo/email'
import { triggerN8nB03Revision } from '@/lib/n8n-outbound'

export interface QaActionResult {
  ok: boolean
  error?: string
}

/**
 * A QA row is ON-DEMAND when it traces back to an on_demand_requests brief —
 * either `flags.request_id` is set (N8N-A02 hold) or its linked post points at
 * an `on_demand_request_id`. Mirrors `classifyQa` in @repo/db/queries/admin.
 *
 * Under Generate-Then-Review, on-demand approve/reject are pure DB status flips
 * (media is already generated by A02): NO N8N-QA-Approved call, NO regeneration.
 * Calendar rows keep their existing behavior (still fire the n8n webhook).
 */
async function resolveOnDemand(
  supabase: ReturnType<typeof adminClient>,
  postId: string | null,
  requestId: string | null,
): Promise<{ isOnDemand: boolean; postId: string | null }> {
  if (requestId) {
    // request_id present → definitively on-demand. Resolve the post: prefer the
    // FK we already have, else the newest calendar_posts row for this brief.
    if (postId) return { isOnDemand: true, postId }
    const { data } = await supabase
      .from('calendar_posts')
      .select('post_id')
      .eq('on_demand_request_id', requestId)
      .order('created_at', { ascending: false })
      .limit(1)
    const resolved = (data as { post_id: string }[] | null)?.[0]?.post_id ?? null
    return { isOnDemand: true, postId: resolved }
  }
  // No request_id: on-demand only if the linked post is on-demand-origin.
  if (postId) {
    const { data } = await supabase
      .from('calendar_posts')
      .select('on_demand_request_id')
      .eq('post_id', postId)
      .maybeSingle()
    const odId = (data as { on_demand_request_id?: string | null } | null)?.on_demand_request_id ?? null
    return { isOnDemand: !!odId, postId }
  }
  return { isOnDemand: false, postId: null }
}

/**
 * Admin "approve" = RELEASE the post to the client. It does NOT mark the post
 * client-approved — the client does that themselves on /[slug]/calendar.
 * Releasing sets status='pending' (in the client-visible filter), so the client
 * sees the post with its AI-Draft watermark + Approve / Request-Revision actions.
 * The client's own Approve is what advances status to 'approved'.
 *
 * This handles a calendar_post with NO qa_review_queue row — an auto-passed
 * (clean/watermark/generated) post the admin opened from the grid. Idempotent.
 */
async function approveCleanPostDirect(
  supabase: ReturnType<typeof adminClient>,
  postId: string,
  decidedBy: string | null,
): Promise<QaActionResult> {
  const { data: post } = await supabase
    .from('calendar_posts')
    .select('post_id, brand_id, status, storage_url')
    .eq('post_id', postId)
    .maybeSingle()
  if (!post) return { ok: false, error: 'post_not_found' }
  const p = post as { post_id: string; brand_id: string; status: string; storage_url: string | null }
  // Already released (pending) or already client-approved → nothing to do.
  if (p.status === 'pending' || p.status === 'approved') return { ok: true } // idempotent
  if (!p.storage_url) return { ok: false, error: 'no_image_yet' }

  const { error } = await supabase
    .from('calendar_posts')
    .update({ status: 'pending' } as never)
    .eq('post_id', postId)
  if (error) return { ok: false, error: error.message }

  await supabase.from('usage_logs').insert({
    flow_id: 'admin_qa', node_name: 'released_clean', brand_id: p.brand_id,
    cost_usd: 0, duration_ms: 0, status: 'success',
    payload: { post_id: postId, decided_by: decidedBy, direct: true } as never,
  } as never)

  revalidatePath('/admin/qa')
  return { ok: true }
}

/**
 * Reject a calendar_post with no qa_review_queue row (admin override on an
 * otherwise-clean post). Pure DB flip to status='rejected'.
 */
async function rejectCleanPostDirect(
  supabase: ReturnType<typeof adminClient>,
  postId: string,
  decidedBy: string | null,
): Promise<QaActionResult> {
  const { data: post } = await supabase
    .from('calendar_posts')
    .select('post_id, brand_id, status')
    .eq('post_id', postId)
    .maybeSingle()
  if (!post) return { ok: false, error: 'post_not_found' }
  const p = post as { post_id: string; brand_id: string; status: string }
  if (p.status === 'rejected') return { ok: true } // idempotent

  const { error } = await supabase
    .from('calendar_posts')
    .update({ status: 'rejected' } as never)
    .eq('post_id', postId)
  if (error) return { ok: false, error: error.message }

  await supabase.from('usage_logs').insert({
    flow_id: 'admin_qa', node_name: 'rejected_clean', brand_id: p.brand_id,
    cost_usd: 0, duration_ms: 0, status: 'success',
    payload: { post_id: postId, decided_by: decidedBy, direct: true } as never,
  } as never)

  revalidatePath('/admin/qa')
  return { ok: true }
}

export async function approveQaItem(queueId: string): Promise<QaActionResult> {
  const admin = await requireAdmin()
  const supabase = adminClient()

  const { data: row, error: fetchErr } = await supabase
    .from('qa_review_queue')
    .select('queue_id, brand_id, post_id, trigger_reason, flags, status')
    .eq('queue_id', queueId)
    .maybeSingle()

  if (fetchErr) return { ok: false, error: fetchErr.message }
  // No queue row — the id is a calendar_post_id for an auto-passed (clean/watermark)
  // post that never needed review. Approve it directly so admin can sign it off.
  if (!row) return approveCleanPostDirect(supabase, queueId, admin.email ?? null)
  if (row.status !== 'pending') return { ok: false, error: `Already ${row.status}` }

  const now = new Date().toISOString()
  const { error: updateErr } = await supabase
    .from('qa_review_queue')
    .update({ status: 'approved', resolved_at: now, reviewed_at: now })
    .eq('queue_id', queueId)
  if (updateErr) return { ok: false, error: updateErr.message }

  await supabase.from('usage_logs').insert({
    flow_id: 'admin_qa',
    node_name: 'approved',
    brand_id: row.brand_id,
    cost_usd: 0,
    duration_ms: 0,
    status: 'success',
    payload: { queue_id: queueId, decided_by: admin.email ?? null } as never,
  } as never)

  const rawPostId  = (row as { post_id?: string | null }).post_id ?? null
  let rawFlags     = (row as { flags?: unknown }).flags
  if (typeof rawFlags === 'string') { try { rawFlags = JSON.parse(rawFlags) } catch { rawFlags = {} } }
  const flags      = (rawFlags as Record<string, unknown> | null) ?? {}
  const requestId  = (flags.request_id as string | null) ?? null

  const { isOnDemand, postId } = await resolveOnDemand(supabase, rawPostId, requestId)
  const now2 = new Date().toISOString()

  // Admin "approve" = RELEASE to the client — a pure DB flip to status='pending'
  // (no n8n workflow; media already exists from the V01 Worker / A02). 'pending'
  // is in the client-visible filter, so the post appears on /[slug]/calendar with
  // its AI-Draft watermark + Approve / Request-Revision. The CLIENT's own Approve
  // is what advances status to 'approved'. Admin approval is NOT client approval.
  if (isOnDemand) {
    if (requestId) {
      await supabase
        .from('on_demand_requests')
        .update({ status: 'delivered', delivered_at: now2 })
        .eq('request_id', requestId)
    }
    if (postId) {
      await supabase
        .from('calendar_posts')
        .update({ status: 'pending' })
        .eq('post_id', postId)
    }
  } else if (postId) {
    // Calendar path — release to client (NO N8N-QA-Approved webhook).
    await supabase
      .from('calendar_posts')
      .update({ status: 'pending' } as never)
      .eq('post_id', postId)
  }

  // AWAIT the notify — fire-and-forget dies when the server action returns
  // (serverless tears down the function before Resend's HTTP call completes,
  // leaving the notification row stuck at 'queued'). The ~1-2s cost guarantees
  // the email is actually sent. notify() never throws, so this can't break approve.
  await fireNotifyQaApproved(supabase, row.brand_id, postId, requestId).catch((e) =>
    console.error('[approveQaItem] notify error:', e),
  )

  revalidatePath('/admin/qa')
  revalidatePath(`/admin/qa/${row.brand_id}`)
  revalidatePath(`/[slug]/calendar`, 'layout')
  revalidatePath(`/[slug]/on-demand`, 'layout')
  return { ok: true }
}

export async function rejectQaItem(queueId: string): Promise<QaActionResult> {
  const admin = await requireAdmin()
  const supabase = adminClient()

  const { data: row, error: fetchErr } = await supabase
    .from('qa_review_queue')
    .select('queue_id, brand_id, post_id, trigger_reason, flags, status')
    .eq('queue_id', queueId)
    .maybeSingle()

  if (fetchErr) return { ok: false, error: fetchErr.message }
  // No queue row — the id is a calendar_post_id for an auto-passed post. Reject
  // it directly (admin override on an otherwise-clean post).
  if (!row) return rejectCleanPostDirect(supabase, queueId, admin.email ?? null)
  if (row.status !== 'pending') return { ok: false, error: `Already ${row.status}` }

  const now = new Date().toISOString()
  const { error: updateErr } = await supabase
    .from('qa_review_queue')
    .update({ status: 'rejected', resolved_at: now, reviewed_at: now })
    .eq('queue_id', queueId)
  if (updateErr) return { ok: false, error: updateErr.message }

  await supabase.from('usage_logs').insert({
    flow_id: 'admin_qa',
    node_name: 'rejected',
    brand_id: row.brand_id,
    cost_usd: 0,
    duration_ms: 0,
    status: 'success',
    payload: { queue_id: queueId, decided_by: admin.email ?? null } as never,
  } as never)

  const rawPostId     = (row as { post_id?: string | null }).post_id ?? null
  let rawFlagsR       = (row as { flags?: unknown }).flags
  if (typeof rawFlagsR === 'string') { try { rawFlagsR = JSON.parse(rawFlagsR) } catch { rawFlagsR = {} } }
  const flags         = (rawFlagsR as Record<string, unknown> | null) ?? {}
  const requestId     = (flags.request_id as string | null) ?? null
  const triggerReason = (row as { trigger_reason?: string | null }).trigger_reason ?? 'quality_review'

  const { isOnDemand, postId } = await resolveOnDemand(supabase, rawPostId, requestId)

  // Reject is a PURE DB STATE FLIP — no n8n workflow. Hide the content from the
  // client (files stay in Storage; soft delete).
  if (isOnDemand) {
    if (requestId) {
      await supabase
        .from('on_demand_requests')
        .update({ status: 'failed', failure_reason: 'admin_rejected' })
        .eq('request_id', requestId)
    }
    if (postId) {
      await supabase
        .from('calendar_posts')
        .update({ status: 'rejected' })
        .eq('post_id', postId)
    }
  } else if (postId) {
    // Calendar path — pure DB flip to rejected (NO n8n webhook).
    await supabase
      .from('calendar_posts')
      .update({ status: 'rejected' } as never)
      .eq('post_id', postId)
  }

  // AWAIT — see approveQaItem note: fire-and-forget dies before Resend completes.
  await fireNotifyQaRejected(supabase, row.brand_id, postId, requestId, triggerReason).catch((e) =>
    console.error('[rejectQaItem] notify error:', e),
  )

  revalidatePath('/admin/qa')
  revalidatePath(`/admin/qa/${row.brand_id}`)
  revalidatePath(`/[slug]/calendar`, 'layout')
  revalidatePath(`/[slug]/on-demand`, 'layout')
  return { ok: true }
}

export interface BulkApproveResult {
  ok: boolean
  approvedCount?: number
  error?: string
}

export async function bulkApproveCalendar(calendarId: string): Promise<BulkApproveResult> {
  const admin = await requireAdmin()
  const supabase = adminClient()

  // Fetch calendar to resolve brand_id
  const { data: calendar, error: calErr } = await supabase
    .from('calendars')
    .select('calendar_id, brand_id')
    .eq('calendar_id', calendarId)
    .maybeSingle()
  if (calErr) return { ok: false, error: calErr.message }
  if (!calendar) return { ok: false, error: 'Calendar not found' }

  const brandId = (calendar as { brand_id: string }).brand_id

  // Resolve which qa_review_queue rows belong to this brand's calendar.
  // qa_review_queue has no calendar_id FK and post_id can be null (pre-image holds),
  // so we classify in-memory via the brand_id pivot.
  const queueIds = await getPendingCalendarQaIdsForBrand(brandId)
  if (queueIds.length === 0) return { ok: true, approvedCount: 0 }

  // Also fetch the calendar's post_ids so we can update calendar_posts status
  const { data: calPosts } = await supabase
    .from('calendar_posts')
    .select('post_id')
    .eq('calendar_id', calendarId)
  const postIds = (calPosts ?? []).map((p) => (p as { post_id: string }).post_id)

  const now = new Date().toISOString()

  // Bulk-approve all pending QA queue rows
  const { error: updateQaErr } = await supabase
    .from('qa_review_queue')
    .update({ status: 'approved', resolved_at: now, reviewed_at: now })
    .in('queue_id', queueIds)
  if (updateQaErr) return { ok: false, error: updateQaErr.message }

  // Bulk admin approve = RELEASE every auto-passed post to the client → status='pending'
  // (client-visible, awaiting the CLIENT's own approval). We only advance posts that
  // are still in a pre-release state; already-released ('pending') or client-approved
  // ('approved') posts are left untouched. Guard the empty array (no WHERE = update all).
  if (postIds.length > 0) {
    await supabase
      .from('calendar_posts')
      .update({ status: 'pending' })
      .in('post_id', postIds)
      .in('status', ['generated', 'clean', 'watermark'])
  }

  // Increment brand_profiles.total_calendars_generated — a TRUE per-calendar count
  // (1,2,3,4...) per doc.md:418. Idempotent via the increment_calendar_count RPC,
  // which flips calendars.counted_in_total exactly once, so re-clicking "Approve
  // All" or a re-run never double-counts this calendar (migration 0107).
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { error: incErr } = await (supabase as any).rpc('increment_calendar_count', {
    p_calendar_id: calendarId,
  })
  if (incErr) console.warn('[bulkApproveCalendar] calendar count increment failed:', incErr.message)

  const { data: brandProfile } = await supabase
    .from('brand_profiles')
    .select('client_slug')
    .eq('brand_id', brandId)
    .maybeSingle()
  const clientSlug = (brandProfile as { client_slug?: string | null } | null)?.client_slug ?? null

  // Mark the calendar itself as approved so the client calendar page shows it
  await supabase
    .from('calendars')
    .update({ status: 'approved' })
    .eq('calendar_id', calendarId)

  // Audit log
  await supabase.from('usage_logs').insert({
    flow_id:     'admin_qa',
    node_name:   'bulk_approved',
    brand_id:    brandId,
    cost_usd:    0,
    duration_ms: 0,
    status:      'success',
    payload:     { calendar_id: calendarId, count: queueIds.length, decided_by: admin.email ?? null } as never,
  } as never)

  // Send "calendar approved" email — AWAITED (fire-and-forget dies before Resend
  // completes in serverless, leaving the row 'queued'). notify() never throws.
  await fireNotifyCalendarApproved(supabase, calendarId, brandId, clientSlug).catch((e) =>
    console.error('[bulkApproveCalendar] notify error:', e),
  )

  revalidatePath('/admin/qa')
  if (clientSlug) {
    revalidatePath(`/${clientSlug}/calendar`)
  }

  return { ok: true, approvedCount: queueIds.length }
}

async function fireNotifyQaApproved(
  db: ReturnType<typeof adminClient>,
  brandId: string,
  postId: string | null,
  requestId: string | null,
) {
  const brandInfo = await adminQ.getBrandForQa(brandId)
  if (!brandInfo?.user_email || !brandInfo.auth_user_id) return

  let position = 0
  let month = ''

  if (postId) {
    // Calendar post path — look up position + month from calendars table
    const { data: post } = await db
      .from('calendar_posts')
      .select('position, calendar_id')
      .eq('post_id', postId)
      .maybeSingle()
    if (post) {
      position = (post as { position: number }).position
      if ((post as { calendar_id?: string | null }).calendar_id) {
        const { data: cal } = await db
          .from('calendars')
          .select('month')
          .eq('calendar_id', (post as { calendar_id: string }).calendar_id)
          .maybeSingle()
        month = (cal as { month?: string } | null)?.month ?? ''
      }
    }
  } else if (requestId) {
    // On-demand post path — postId is null at notify time (image still generating).
    // Use the request's posting_time to derive a meaningful month for the email.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: req } = await (db as any)
      .from('on_demand_requests')
      .select('posting_time, content_type, platform')
      .eq('request_id', requestId)
      .maybeSingle()
    if (req) {
      const pt = (req as { posting_time?: string | null }).posting_time
      month = pt ? pt.slice(0, 7) : new Date().toISOString().slice(0, 7)
    }
  }

  await notify({
    templateKey: 'post_approved',
    variables: {
      brand_name: brandInfo.brand_name_ar,
      position,
      month,
    },
    brandId,
    authUserId: brandInfo.auth_user_id,
    userEmail: brandInfo.user_email,
    postId: postId ?? undefined,
  })
}

async function fireNotifyCalendarApproved(
  db: ReturnType<typeof adminClient>,
  calendarId: string,
  brandId: string,
  clientSlug: string | null,
) {
  // Fetch calendar month + flag in one query.
  const { data: cal } = await db
    .from('calendars')
    .select('month, approved_email_sent')
    .eq('calendar_id', calendarId)
    .maybeSingle()

  if (!cal) return

  const calRow = cal as { month: string; approved_email_sent: boolean }
  if (calRow.approved_email_sent) return

  // Atomic compare-and-set — skip if another concurrent call already won.
  const { count } = await db
    .from('calendars')
    .update({ approved_email_sent: true })
    .eq('calendar_id', calendarId)
    .eq('approved_email_sent', false)
    .select('calendar_id')
  if ((count ?? 0) === 0) return

  const brandInfo = await adminQ.getBrandForQa(brandId)
  if (!brandInfo?.user_email || !brandInfo.auth_user_id) return

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'
  const calendarUrl = clientSlug
    ? `${appUrl}/${clientSlug}/calendar/${calRow.month}`
    : `${appUrl}/dashboard`

  await notify({
    templateKey: 'calendar_approved',
    variables: {
      brand_name:   brandInfo.brand_name_ar,
      month:        calRow.month,
      calendar_url: calendarUrl,
    },
    brandId,
    authUserId: brandInfo.auth_user_id,
    userEmail:  brandInfo.user_email,
    calendarId,
  })
}

async function fireNotifyQaRejected(
  db: ReturnType<typeof adminClient>,
  brandId: string,
  postId: string | null,
  requestId: string | null,
  triggerReason: string,
) {
  const brandInfo = await adminQ.getBrandForQa(brandId)
  if (!brandInfo?.user_email || !brandInfo.auth_user_id) return

  let position = 0

  if (postId) {
    const { data: post } = await db
      .from('calendar_posts')
      .select('position')
      .eq('post_id', postId)
      .maybeSingle()
    if (post) position = (post as { position: number }).position
  }

  await notify({
    templateKey: 'post_rejected',
    variables: {
      brand_name: brandInfo.brand_name_ar,
      position,
      reason: triggerReason,
    },
    brandId,
    authUserId: brandInfo.auth_user_id,
    userEmail: brandInfo.user_email,
    postId: postId ?? undefined,
  })
}

// ─────────────────────────────────────────────────────────────────────────────
// Request revision — marks QA item as 'revision_requested', updates the post
// status, and fires the N8N-B03 revision webhook with the admin's notes.
// ─────────────────────────────────────────────────────────────────────────────

export interface RevisionResult {
  ok: boolean
  error?: string
}

export async function requestRevision(
  queueId: string,
  revisionNotes: string,
): Promise<RevisionResult> {
  const admin = await requireAdmin()
  const supabase = adminClient()

  const { data: row, error: fetchErr } = await supabase
    .from('qa_review_queue')
    .select('queue_id, brand_id, post_id, trigger_reason, flags, status')
    .eq('queue_id', queueId)
    .maybeSingle()

  if (fetchErr) return { ok: false, error: fetchErr.message }
  if (!row) return { ok: false, error: 'qa_item_not_found' }
  if (row.status !== 'pending') return { ok: false, error: `Already ${row.status}` }

  const now = new Date().toISOString()
  const { error: updateErr } = await supabase
    .from('qa_review_queue')
    .update({ status: 'revision_requested', reviewed_at: now } as never)
    .eq('queue_id', queueId)
  if (updateErr) return { ok: false, error: updateErr.message }

  const postId    = (row as { post_id?: string | null }).post_id ?? null
  const brandId   = row.brand_id

  // Bump revision_count on the post and record admin feedback
  if (postId) {
    await supabase
      .from('calendar_posts')
      .update({
        status:         'draft',
        revision_count: supabase.rpc as never,
      } as never)
      .eq('post_id', postId)

    // Simple increment without RPC: read then write
    const { data: postRow } = await supabase
      .from('calendar_posts')
      .select('revision_count')
      .eq('post_id', postId)
      .maybeSingle()
    const newCount = ((postRow as { revision_count?: number } | null)?.revision_count ?? 0) + 1
    await supabase
      .from('calendar_posts')
      .update({ status: 'draft', revision_count: newCount } as never)
      .eq('post_id', postId)
  }

  // Audit log
  await supabase.from('usage_logs').insert({
    flow_id:     'admin_qa',
    node_name:   'revision_requested',
    brand_id:    brandId,
    cost_usd:    0,
    duration_ms: 0,
    status:      'success',
    payload:     { queue_id: queueId, post_id: postId, decided_by: admin.email ?? null, notes: revisionNotes } as never,
  } as never)

  // Fire N8N-B03 — revision loop
  triggerN8nB03Revision({
    brand_id:       brandId,
    queue_id:       queueId,
    post_id:        postId,
    revision_notes: revisionNotes,
    requested_by:   admin.email ?? 'admin',
  }).catch(() => {})

  revalidatePath('/admin/qa')
  return { ok: true }
}
