/**
 * Phase B — Internal Content Release Gate
 *
 * All posts generated by N8N-A01 that passed the 11 CCO/CEO quality triggers
 * (status='generated') land here for OGZ admin review BEFORE the client
 * calendar shows them. This fulfils OGZ §5.4 "Day -7" principle:
 * every AI-generated post must be seen by an OGZ reviewer first.
 *
 * Flow: status='generated' → admin reviews here → "Release" → status='pending'
 *       → client calendar shows it → client approves → status='approved' → P01
 */
import { adminQ } from '@repo/db'
import { PageHeader } from '@repo/ui/page-header'
import { Badge } from '@repo/ui/badge'
import { ReleasePostButton, ReleaseAllButton } from './release-buttons'

export const dynamic = 'force-dynamic'

export default async function ContentReleasePage() {
  const posts = await adminQ.getUnreleasedPosts(300)

  // Group by brand
  const grouped = new Map<string, { brand_name_ar: string; client_slug: string; posts: typeof posts }>()
  for (const post of posts) {
    if (!grouped.has(post.brand_id)) {
      grouped.set(post.brand_id, { brand_name_ar: post.brand_name_ar, client_slug: post.client_slug, posts: [] })
    }
    grouped.get(post.brand_id)!.posts.push(post)
  }

  const brands = Array.from(grouped.entries()).sort((a, b) =>
    a[1].brand_name_ar.localeCompare(b[1].brand_name_ar, 'ar'),
  )

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Phase B — OGZ §5.4"
        title="Content Release Gate"
        subtitle="Every AI-generated post must be reviewed here before clients can see it. Release each post (or all posts for a brand) when it passes internal review."
      />

      {/* Policy notice */}
      <div className="flex flex-wrap items-center gap-3 rounded-(--r-lg) border border-amber-500/30 bg-amber-500/5 px-4 py-3 text-xs text-amber-400">
        <svg className="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
        </svg>
        <span>
          <strong>Saudi market requirement:</strong> Religion and culture are priority.
          Content that reaches clients without OGZ approval is an operational risk.
          Review caption and image before releasing — especially for posts touching religion, family, or health topics.
        </span>
      </div>

      {posts.length === 0 ? (
        <div className="flex flex-col items-center justify-center rounded-(--r-lg) border border-(--border-subtle) bg-(--surface-2) px-6 py-16 text-center">
          <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-emerald-500/10">
            <svg className="h-6 w-6 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
            </svg>
          </div>
          <p className="text-sm font-medium text-(--fg)">All clear</p>
          <p className="mt-1 text-xs text-(--fg-faint)">No posts are waiting for internal review.</p>
        </div>
      ) : (
        <div className="space-y-6">
          {brands.map(([brandId, { brand_name_ar, client_slug, posts: brandPosts }]) => (
            <div key={brandId} className="rounded-(--r-lg) border border-(--border-subtle) bg-(--surface-2) overflow-hidden">
              {/* Brand header */}
              <div className="flex items-center justify-between gap-4 border-b border-(--border-subtle) bg-(--surface-3) px-5 py-3">
                <div className="flex items-center gap-3">
                  <div dir="rtl">
                    <span className="font-semibold text-(--fg)">{brand_name_ar}</span>
                    <span className="ml-2 text-xs text-(--fg-faint)">/{client_slug}</span>
                  </div>
                  <Badge tone="warning" size="sm">{brandPosts.length} pending</Badge>
                </div>
                <ReleaseAllButton brandId={brandId} count={brandPosts.length} />
              </div>

              {/* Posts table */}
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-(--border-subtle) text-left text-(--fg-faint)">
                    <th className="px-5 py-2 font-medium">#</th>
                    <th className="px-4 py-2 font-medium">Caption (AR)</th>
                    <th className="px-4 py-2 font-medium">Month</th>
                    <th className="px-4 py-2 font-medium">Type</th>
                    <th className="px-4 py-2 font-medium">Posting time</th>
                    <th className="px-4 py-2 font-medium text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-(--border-subtle)">
                  {brandPosts.map((post) => (
                    <tr key={post.post_id} className="hover:bg-(--surface-3) transition-colors">
                      <td className="px-5 py-3 font-mono text-(--fg-muted)">{post.position}</td>
                      <td className="px-4 py-3 max-w-sm">
                        <p dir="rtl" className="line-clamp-2 text-(--fg)">{post.caption_ar ?? '—'}</p>
                      </td>
                      <td className="px-4 py-3 text-(--fg-muted)">{post.calendar_month ?? '—'}</td>
                      <td className="px-4 py-3">
                        <Badge tone="neutral" size="sm">{post.content_type ?? '—'}</Badge>
                      </td>
                      <td className="px-4 py-3 text-(--fg-muted)">
                        {post.posting_time
                          ? new Date(post.posting_time).toLocaleDateString('en-GB', {
                              day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit',
                            })
                          : '—'}
                      </td>
                      <td className="px-4 py-3 text-right">
                        <ReleasePostButton postId={post.post_id} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
