-- OpenClaw — 0099_admin_regenerations
-- Admin-side Regenerate for on-demand content.
--
-- Why a new table (admin_regenerations):
--   The user-side Regenerate flow (N8N-B03) overwrites calendar_posts.storage_url
--   IN PLACE and bumps revision_count — so anything B03 produces is immediately
--   user-visible. Admins need to regenerate on-demand posts WITHOUT exposing the
--   result to the client until an admin explicitly approves it. We therefore give
--   admin regenerations a separate "draft lane": each admin regeneration becomes a
--   row here (a version), and calendar_posts stays the single published source of
--   truth. On admin approval the chosen draft is promoted into calendar_posts.
--
--   This keeps the user's own regeneration history (calendar_posts.revision_count /
--   revision_history) completely independent of the admin draft history.
--
-- Visibility:
--   RLS is enabled with ONLY a service_role policy. No anon/authenticated policy
--   exists, so RLS denies by default for clients — admin drafts can never leak to
--   users. The app reads/writes this table exclusively through the service-role
--   adminClient (admin server actions + admin QA queue enrichment).
--
-- Hard Rules respected:
--   #3 prompt_override is English-only (Arabic overlay applied post-generation).
--   #4 storage_url is always a Supabase Storage URL (B03/V01 re-upload from Weavy).
--
-- Idempotent: guarded with IF NOT EXISTS / do-blocks.

begin;

-- ─────────────────────────────────────────────────────────
-- 1. Enum — admin regeneration lifecycle
-- ─────────────────────────────────────────────────────────
do $$ begin
  create type admin_regen_status_type as enum (
    'draft',       -- generated by B03 (target=admin), awaiting admin decision
    'approved',    -- admin promoted this version into calendar_posts (now live)
    'rejected',    -- admin discarded this version (stays in history)
    'superseded'   -- another version for the same post was approved instead
  );
exception when duplicate_object then null; end $$;

-- ─────────────────────────────────────────────────────────
-- 2. admin_regenerations — one row per admin draft version
-- ─────────────────────────────────────────────────────────
create table if not exists public.admin_regenerations (
  regen_id          uuid primary key default gen_random_uuid(),
  post_id           uuid not null references public.calendar_posts(post_id) on delete cascade,
  request_id        uuid references public.on_demand_requests(request_id) on delete set null,
  brand_id          uuid not null,
  version           integer not null,
  media_type        text not null default 'image',
  storage_url       text not null,
  clean_storage_url text,
  caption_ar        text,
  hashtags          text[] not null default '{}',
  confidence_score  numeric,
  watermark         boolean not null default false,
  prompt_override   jsonb,
  image_model       text,
  status            admin_regen_status_type not null default 'draft',
  created_by        text,
  created_at        timestamptz not null default now(),
  reviewed_at       timestamptz,
  reviewed_by       text
);

-- ─────────────────────────────────────────────────────────
-- 3. Indexes
-- ─────────────────────────────────────────────────────────
create index if not exists idx_admin_regen_post_version
  on public.admin_regenerations (post_id, version desc);
create index if not exists idx_admin_regen_status
  on public.admin_regenerations (status);

-- ─────────────────────────────────────────────────────────
-- 4. RLS — admin/service-role only. No client policy → clients denied.
-- ─────────────────────────────────────────────────────────
alter table public.admin_regenerations enable row level security;

drop policy if exists admin_full on public.admin_regenerations;
create policy admin_full on public.admin_regenerations
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

commit;
