-- 0108_fix_chain_library_data.sql
-- Corrects three data issues in the chains table vs OGz 2.0 ChainLibrary v2 Complete doc:
--   1. family off-by-one (22 boundary chains mis-tagged with the previous family) — bug originated in 0071 seed.
--   2. missing fal_model_secondary (image->video variant) on 15 image chains the doc lists video variants for.
--   3. empty eligible_occasions on 15 occasion-targeted chains the doc specifies occasions for.
-- Idempotent: pure UPDATEs keyed by chain_id. Safe to re-run.

BEGIN;

-- 1) Correct family assignments (per doc inventory TF01..TF23)
UPDATE chains SET family='TF01', updated_at=now() WHERE chain_id='U01' AND family IS DISTINCT FROM 'TF01';
UPDATE chains SET family='TF01', updated_at=now() WHERE chain_id='T01' AND family IS DISTINCT FROM 'TF01';
UPDATE chains SET family='TF01', updated_at=now() WHERE chain_id='T02' AND family IS DISTINCT FROM 'TF01';
UPDATE chains SET family='TF02', updated_at=now() WHERE chain_id='T03' AND family IS DISTINCT FROM 'TF02';
UPDATE chains SET family='TF02', updated_at=now() WHERE chain_id='T04' AND family IS DISTINCT FROM 'TF02';
UPDATE chains SET family='TF02', updated_at=now() WHERE chain_id='T05' AND family IS DISTINCT FROM 'TF02';
UPDATE chains SET family='TF02', updated_at=now() WHERE chain_id='T06' AND family IS DISTINCT FROM 'TF02';
UPDATE chains SET family='TF02', updated_at=now() WHERE chain_id='T07' AND family IS DISTINCT FROM 'TF02';
UPDATE chains SET family='TF03', updated_at=now() WHERE chain_id='T08' AND family IS DISTINCT FROM 'TF03';
UPDATE chains SET family='TF03', updated_at=now() WHERE chain_id='T09' AND family IS DISTINCT FROM 'TF03';
UPDATE chains SET family='TF03', updated_at=now() WHERE chain_id='T10' AND family IS DISTINCT FROM 'TF03';
UPDATE chains SET family='TF03', updated_at=now() WHERE chain_id='T11' AND family IS DISTINCT FROM 'TF03';
UPDATE chains SET family='TF04', updated_at=now() WHERE chain_id='T12' AND family IS DISTINCT FROM 'TF04';
UPDATE chains SET family='TF04', updated_at=now() WHERE chain_id='T13' AND family IS DISTINCT FROM 'TF04';
UPDATE chains SET family='TF04', updated_at=now() WHERE chain_id='T14' AND family IS DISTINCT FROM 'TF04';
UPDATE chains SET family='TF04', updated_at=now() WHERE chain_id='T15' AND family IS DISTINCT FROM 'TF04';
UPDATE chains SET family='TF04', updated_at=now() WHERE chain_id='T16' AND family IS DISTINCT FROM 'TF04';
UPDATE chains SET family='TF05', updated_at=now() WHERE chain_id='T17' AND family IS DISTINCT FROM 'TF05';
UPDATE chains SET family='TF05', updated_at=now() WHERE chain_id='T18' AND family IS DISTINCT FROM 'TF05';
UPDATE chains SET family='TF05', updated_at=now() WHERE chain_id='T19' AND family IS DISTINCT FROM 'TF05';
UPDATE chains SET family='TF05', updated_at=now() WHERE chain_id='T20' AND family IS DISTINCT FROM 'TF05';
UPDATE chains SET family='TF06', updated_at=now() WHERE chain_id='T21' AND family IS DISTINCT FROM 'TF06';
UPDATE chains SET family='TF06', updated_at=now() WHERE chain_id='T22' AND family IS DISTINCT FROM 'TF06';
UPDATE chains SET family='TF06', updated_at=now() WHERE chain_id='T23' AND family IS DISTINCT FROM 'TF06';
UPDATE chains SET family='TF07', updated_at=now() WHERE chain_id='T24' AND family IS DISTINCT FROM 'TF07';
UPDATE chains SET family='TF07', updated_at=now() WHERE chain_id='T25' AND family IS DISTINCT FROM 'TF07';
UPDATE chains SET family='TF07', updated_at=now() WHERE chain_id='T26' AND family IS DISTINCT FROM 'TF07';
UPDATE chains SET family='TF07', updated_at=now() WHERE chain_id='T27' AND family IS DISTINCT FROM 'TF07';
UPDATE chains SET family='TF08', updated_at=now() WHERE chain_id='T28' AND family IS DISTINCT FROM 'TF08';
UPDATE chains SET family='TF08', updated_at=now() WHERE chain_id='T29' AND family IS DISTINCT FROM 'TF08';
UPDATE chains SET family='TF08', updated_at=now() WHERE chain_id='T30' AND family IS DISTINCT FROM 'TF08';
UPDATE chains SET family='TF08', updated_at=now() WHERE chain_id='T31' AND family IS DISTINCT FROM 'TF08';
UPDATE chains SET family='TF08', updated_at=now() WHERE chain_id='T32' AND family IS DISTINCT FROM 'TF08';
UPDATE chains SET family='TF09', updated_at=now() WHERE chain_id='T33' AND family IS DISTINCT FROM 'TF09';
UPDATE chains SET family='TF09', updated_at=now() WHERE chain_id='T34' AND family IS DISTINCT FROM 'TF09';
UPDATE chains SET family='TF09', updated_at=now() WHERE chain_id='T35' AND family IS DISTINCT FROM 'TF09';
UPDATE chains SET family='TF09', updated_at=now() WHERE chain_id='T36' AND family IS DISTINCT FROM 'TF09';
UPDATE chains SET family='TF09', updated_at=now() WHERE chain_id='T37' AND family IS DISTINCT FROM 'TF09';
UPDATE chains SET family='TF10', updated_at=now() WHERE chain_id='T38' AND family IS DISTINCT FROM 'TF10';
UPDATE chains SET family='TF10', updated_at=now() WHERE chain_id='T39' AND family IS DISTINCT FROM 'TF10';
UPDATE chains SET family='TF10', updated_at=now() WHERE chain_id='T40' AND family IS DISTINCT FROM 'TF10';
UPDATE chains SET family='TF11', updated_at=now() WHERE chain_id='T41' AND family IS DISTINCT FROM 'TF11';
UPDATE chains SET family='TF11', updated_at=now() WHERE chain_id='T42' AND family IS DISTINCT FROM 'TF11';
UPDATE chains SET family='TF11', updated_at=now() WHERE chain_id='T43' AND family IS DISTINCT FROM 'TF11';
UPDATE chains SET family='TF12', updated_at=now() WHERE chain_id='T44' AND family IS DISTINCT FROM 'TF12';
UPDATE chains SET family='TF12', updated_at=now() WHERE chain_id='T45' AND family IS DISTINCT FROM 'TF12';
UPDATE chains SET family='TF12', updated_at=now() WHERE chain_id='T46' AND family IS DISTINCT FROM 'TF12';
UPDATE chains SET family='TF13', updated_at=now() WHERE chain_id='U04' AND family IS DISTINCT FROM 'TF13';
UPDATE chains SET family='TF13', updated_at=now() WHERE chain_id='U05' AND family IS DISTINCT FROM 'TF13';
UPDATE chains SET family='TF13', updated_at=now() WHERE chain_id='F02' AND family IS DISTINCT FROM 'TF13';
UPDATE chains SET family='TF13', updated_at=now() WHERE chain_id='T47' AND family IS DISTINCT FROM 'TF13';
UPDATE chains SET family='TF13', updated_at=now() WHERE chain_id='T48' AND family IS DISTINCT FROM 'TF13';
UPDATE chains SET family='TF13', updated_at=now() WHERE chain_id='T49' AND family IS DISTINCT FROM 'TF13';
UPDATE chains SET family='TF13', updated_at=now() WHERE chain_id='T50' AND family IS DISTINCT FROM 'TF13';
UPDATE chains SET family='TF14', updated_at=now() WHERE chain_id='T51' AND family IS DISTINCT FROM 'TF14';
UPDATE chains SET family='TF14', updated_at=now() WHERE chain_id='T52' AND family IS DISTINCT FROM 'TF14';
UPDATE chains SET family='TF14', updated_at=now() WHERE chain_id='T53' AND family IS DISTINCT FROM 'TF14';
UPDATE chains SET family='TF15', updated_at=now() WHERE chain_id='U02' AND family IS DISTINCT FROM 'TF15';
UPDATE chains SET family='TF15', updated_at=now() WHERE chain_id='F04' AND family IS DISTINCT FROM 'TF15';
UPDATE chains SET family='TF15', updated_at=now() WHERE chain_id='R03' AND family IS DISTINCT FROM 'TF15';
UPDATE chains SET family='TF16', updated_at=now() WHERE chain_id='U03' AND family IS DISTINCT FROM 'TF16';
UPDATE chains SET family='TF16', updated_at=now() WHERE chain_id='F03' AND family IS DISTINCT FROM 'TF16';
UPDATE chains SET family='TF17', updated_at=now() WHERE chain_id='B01' AND family IS DISTINCT FROM 'TF17';
UPDATE chains SET family='TF17', updated_at=now() WHERE chain_id='B02' AND family IS DISTINCT FROM 'TF17';
UPDATE chains SET family='TF18', updated_at=now() WHERE chain_id='B03' AND family IS DISTINCT FROM 'TF18';
UPDATE chains SET family='TF18', updated_at=now() WHERE chain_id='B05' AND family IS DISTINCT FROM 'TF18';
UPDATE chains SET family='TF18', updated_at=now() WHERE chain_id='R01' AND family IS DISTINCT FROM 'TF18';
UPDATE chains SET family='TF18', updated_at=now() WHERE chain_id='R04' AND family IS DISTINCT FROM 'TF18';
UPDATE chains SET family='TF19', updated_at=now() WHERE chain_id='R02' AND family IS DISTINCT FROM 'TF19';
UPDATE chains SET family='TF20', updated_at=now() WHERE chain_id='R05' AND family IS DISTINCT FROM 'TF20';
UPDATE chains SET family='TF20', updated_at=now() WHERE chain_id='F05' AND family IS DISTINCT FROM 'TF20';
UPDATE chains SET family='TF21', updated_at=now() WHERE chain_id='B04' AND family IS DISTINCT FROM 'TF21';
UPDATE chains SET family='TF21', updated_at=now() WHERE chain_id='U06' AND family IS DISTINCT FROM 'TF21';
UPDATE chains SET family='TF22', updated_at=now() WHERE chain_id='V01' AND family IS DISTINCT FROM 'TF22';
UPDATE chains SET family='TF22', updated_at=now() WHERE chain_id='V02' AND family IS DISTINCT FROM 'TF22';
UPDATE chains SET family='TF22', updated_at=now() WHERE chain_id='V03' AND family IS DISTINCT FROM 'TF22';
UPDATE chains SET family='TF22', updated_at=now() WHERE chain_id='V04' AND family IS DISTINCT FROM 'TF22';
UPDATE chains SET family='TF22', updated_at=now() WHERE chain_id='V05' AND family IS DISTINCT FROM 'TF22';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S01' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S02' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S03' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S04' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S05' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S06' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S07' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S08' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S09' AND family IS DISTINCT FROM 'TF23';
UPDATE chains SET family='TF23', updated_at=now() WHERE chain_id='S10' AND family IS DISTINCT FROM 'TF23';

-- 2) Add image->video variant models (only image chains the doc gives a video variant for)
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='U01' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T01' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T02' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T03' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T04' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T05' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T06' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T07' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T08' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T09' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T10' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T11' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T12' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T13' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T14' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T15' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T16' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T17' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T18' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T19' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T20' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T21' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T22' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T23' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T24' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T25' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T26' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T27' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T28' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T29' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T30' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T31' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T32' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T33' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T34' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T35' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T36' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T37' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T41' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T42' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T43' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T44' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T45' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T46' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='U04' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='F02' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T47' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T48' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T49' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T50' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='T51' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T52' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='T53' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='U03' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='F03' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='B01' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='B02' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='B03' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='B05' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='R01' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='R04' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='R02' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='R05' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='F05' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='B04' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='U06' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='S01' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='S02' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='S03' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='S04' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='S05' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='S06' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='S07' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='S08' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/kling-video/v1.6/pro/image-to-video', updated_at=now() WHERE chain_id='S09' AND fal_model_secondary IS NULL;
UPDATE chains SET fal_model_secondary='fal-ai/seedance-2.0', updated_at=now() WHERE chain_id='S10' AND fal_model_secondary IS NULL;

-- 3) Populate eligible_occasions where the doc specifies occasion targeting
UPDATE chains SET eligible_occasions=ARRAY['summer','ramadan']::text[], updated_at=now() WHERE chain_id='T04' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['summer']::text[], updated_at=now() WHERE chain_id='T06' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['valentine','mothers_day','eid']::text[], updated_at=now() WHERE chain_id='T25' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['gifting']::text[], updated_at=now() WHERE chain_id='T26' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['spring']::text[], updated_at=now() WHERE chain_id='T27' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['national_day','founding_day']::text[], updated_at=now() WHERE chain_id='T30' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['valentine','mothers_day','eid']::text[], updated_at=now() WHERE chain_id='T42' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['ramadan','eid','national_day']::text[], updated_at=now() WHERE chain_id='U02' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['ramadan','eid','national_day','founding_day']::text[], updated_at=now() WHERE chain_id='U03' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['ramadan']::text[], updated_at=now() WHERE chain_id='F03' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['wedding_season']::text[], updated_at=now() WHERE chain_id='B05' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['ramadan']::text[], updated_at=now() WHERE chain_id='V01' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['national_day','founding_day','eid']::text[], updated_at=now() WHERE chain_id='V04' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['ramadan']::text[], updated_at=now() WHERE chain_id='S03' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['mothers_day','eid']::text[], updated_at=now() WHERE chain_id='S09' AND COALESCE(array_length(eligible_occasions,1),0)=0;
UPDATE chains SET eligible_occasions=ARRAY['national_day','founding_day']::text[], updated_at=now() WHERE chain_id='S10' AND COALESCE(array_length(eligible_occasions,1),0)=0;

COMMIT;
