/**
 * POST /api/agents/cco/qc
 *
 * CCO Arabic QC (Doc §6.3). Called by N8N-A01 / N8N-A02 AFTER DeepSeek and
 * BEFORE the CEO confidence gate. Returns one evaluation per post.
 *
 * Phase 0 — Compliance Gate (Spine-02):
 *   Before calling the LLM, every caption is checked deterministically using
 *   two layers:
 *
 *   Layer 1 — @repo/ai checkHardBlocksWithContext (pure in-memory keyword scan
 *   against the 10 hard-block violation patterns from spec §11.1). Zero DB
 *   calls, O(n) scan. Seasonal block (food_consumption_ramadan_daylight) is
 *   skipped unless occasion_flags includes 'ramadan'. cross_gender_contact is
 *   skipped unless religious_sensitivity is 'High'.
 *
 *   Layer 2 — Brand-specific HARD_BLOCK patterns from negative_patterns table
 *   (written by Memory Controller). Catches brand-level anti-attributes that
 *   were escalated to hard blocks after repeated violations.
 *
 *   Posts that fail either layer get score=0, negpat_flag='HARD_BLOCK' with no
 *   LLM tokens spent. Only posts that clear both layers proceed to the LLM.
 *   Results are merged back in original input order.
 *
 * Model selection: GPT-5 if OPENAI_CCO_MODEL=gpt-5 (Tier 4 confirmed);
 * otherwise GPT-4o (Doc §13.1).
 */
import { adminClient } from '@repo/db/client'
import { cco, checkHardBlocksWithContext } from '@repo/ai'
import { z } from 'zod'
import { schemas } from '@repo/core'
import { makeAgentRoute } from '@/lib/agent-route'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const RequestBody = z.object({
  flow_id: z.string().min(1),
  brand_id: z.string().uuid(),
  payload: z.object({
    caption_context_excerpt: z.string().min(1),
    posts: z
      .array(
        z.object({
          post_id: z.string(),
          caption_ar: z.string().min(1),
          content_type: z.string().optional(),
          hashtags: z.array(z.string()).optional(),
          posting_time: z.string().optional(),
          // Scoring hints generated by DeepSeek — forwarded to the CCO LLM.
          positive_keywords: z.array(z.string()).optional().default([]),
          negative_keywords: z.array(z.string()).optional().default([]),
          // v2 method-adherence inputs — the visual brief (Component 3) and the
          // post objective (Component 4). Optional for backward compatibility.
          visual_brief_en: z.string().optional(),
          objective: z.string().optional(),
        }),
      )
      .min(1)
      .max(50),
    // Active occasion flags — used for seasonal hard-block activation
    occasion_flags: z.array(z.string()).optional(),
    // Brand's religious sensitivity — activates cross_gender_contact block
    religious_sensitivity: z.enum(['Low', 'Medium', 'High']).optional(),
    // Structured brand method profile (BrandDNA v2). When present, the CCO can
    // grade the 30% method-adherence weight; when absent it defaults to neutral.
    method_profile: z
      .object({
        voice_register: z.string().optional(),
        diagnostic_pattern: z.string().optional(),
        visual_idiom: z.string().optional(),
        cadence_rule: z.string().optional(),
        closing_pattern: z.string().optional(),
      })
      .optional(),
  }),
})

type BrandNegativePattern = { pattern_value: string; severity: string }

async function loadBrandHardBlocks(
  db: ReturnType<typeof adminClient>,
  brandId: string,
): Promise<string[]> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data } = await (db as any)
    .from('negative_patterns')
    .select('pattern_value, severity')
    .eq('brand_id', brandId)
    .eq('severity', 'HARD_BLOCK')
  return ((data ?? []) as BrandNegativePattern[]).map((r) => r.pattern_value.toLowerCase())
}

export const POST = makeAgentRoute({
  inputSchema: RequestBody,
  defaultFlowId: 'N8N-A01',
  handler: async (input, ctx) => {
    const db = adminClient()
    const { posts, caption_context_excerpt, occasion_flags = [], religious_sensitivity = 'Medium', method_profile } = input.payload
    const ramadanActive = occasion_flags.includes('ramadan')

    // ── Layer 2: load brand-specific HARD_BLOCK patterns ─────────────────────
    let brandHardBlocks: string[] = []
    try {
      brandHardBlocks = await loadBrandHardBlocks(db, input.brand_id)
    } catch (e) {
      // Non-fatal — Layer 1 still runs. Log loudly so ops notices.
      console.error(`[compliance-gate] brand pattern load FAILED brand=${input.brand_id}: ${(e as Error).message}`)
    }

    // ── Deterministic gate: check every post before any LLM call ─────────────
    const blocked: schemas.CcoPostEvaluation[] = []
    const passing: typeof posts = []

    for (const post of posts) {
      // Layer 1: universal keyword scan (in-memory, zero cost)
      const texts = [post.caption_ar, ...(post.hashtags ?? [])]
      const gate = checkHardBlocksWithContext(texts, { ramadan_active: ramadanActive })

      // cross_gender_contact only applies to High religious sensitivity brands
      const effectiveViolations = gate.violations.filter((v) =>
        v.code !== 'cross_gender_contact' || religious_sensitivity === 'High',
      )

      if (effectiveViolations.length > 0) {
        console.warn(
          `[compliance-gate] HARD_BLOCK (universal) post=${post.post_id} brand=${input.brand_id} ` +
            `code=${effectiveViolations[0]!.code} match="${effectiveViolations[0]!.match}"`,
        )
        blocked.push({
          post_id:          post.post_id,
          score:            0,
          dialect_flag:     false,
          negpat_flag:      'HARD_BLOCK',
          cultural_flag:    true,
          brave_route_flag: false,
          issues:           ['cultural_insensitivity'],
        })
        continue
      }

      // Layer 2: brand-specific hard block substring match
      const captionLower = post.caption_ar.toLowerCase()
      const brandViolation = brandHardBlocks.find((pattern) => pattern && captionLower.includes(pattern))
      if (brandViolation) {
        console.warn(
          `[compliance-gate] HARD_BLOCK (brand-specific) post=${post.post_id} brand=${input.brand_id} ` +
            `pattern="${brandViolation}"`,
        )
        blocked.push({
          post_id:          post.post_id,
          score:            0,
          dialect_flag:     false,
          negpat_flag:      'HARD_BLOCK',
          cultural_flag:    true,
          brave_route_flag: false,
          issues:           ['anti_attribute_violation'],
        })
        continue
      }

      passing.push(post)
    }

    // ── LLM QC — only on posts that cleared both gate layers ─────────────────
    if (passing.length === 0) {
      // All posts deterministically blocked — return with zero LLM spend
      return blocked
    }

    const llmResult = await cco.qcCaptions(
      {
        brand_id:                input.brand_id,
        caption_context_excerpt,
        posts:                   passing,
        // Structured method profile — lets the CCO grade method adherence
        // (30% of the score) instead of defaulting to neutral. Omitted cleanly
        // when the caption context carried no method profile.
        ...(method_profile ? { method_profile } : {}),
      },
      { flow_id: ctx.flowId, brand_id: input.brand_id, db },
    )

    // Merge blocked + LLM results, preserving original input order
    const evalMap = new Map<string, schemas.CcoPostEvaluation>()
    for (const ev of [...blocked, ...llmResult]) evalMap.set(ev.post_id, ev)

    return posts.map(
      (p) =>
        evalMap.get(p.post_id) ?? {
          post_id:          p.post_id,
          score:            0,
          dialect_flag:     false,
          negpat_flag:      'HARD_BLOCK' as const,
          cultural_flag:    true,
          brave_route_flag: false,
          issues:           ['evaluation_failed'],
        },
    )
  },
})
